### ISSUE TITLE
bad license text

### ISSUE THREAD

**Issue by Alexey-T** [PierceNg/fpwebview#2]
1. GH repo tells

The code is under MIT license, with following exceptions: 

2. code in webview.pas tells

This Source Code Form is subject to the terms of the Mozilla Public
License

**Comment by PierceNg** [comment]
Main README says:

> This repo is under MIT license, with following exceptions:
> - The source file(s) that make up the ```webview``` Pascal unit are licensed under MPLv2. 
> - ...

Based on my IANAL understanding, MPLv2 is a file-level license, hence ```webview.pas``` carries the MPLv2 notice in it.

My intent is that the ```webview``` unit - currently only one source file, could be more in future - be licensed under MPLv2, while the rest of the repo is under MIT. (And Microsoft's DLL is per their license.)

**Comment by PierceNg** [comment]
Thinking about it some more:

- Anybody who knows Pascal FFI can easily create the ```webview``` API declaration.
- It is possible to create a proprietary higher-level Object Pascal wrapper for this API in a separate file, so that the wrapper isn't tainted by MPLv2, yet remains in compliance.

Ok, I don't want to spend too much time thinking about this licensing stuff. Let's just leave this as is for now.
