### ISSUE TITLE
Not working Mouse Cursor and Hover Mouse Events on MacOS in fpwebview/demo/lclembed demo

### ISSUE THREAD

**Issue by commanderz** [PierceNg/fpwebview#6]
Not working Mouse Cursor and Hover Mouse Events on MacOS in fpwebview/demo/lclembed demo
but with cli demo all work fine, maybe very complicated method for this.

that is, when hovering over a button/text/edit, the mouse cursor does not change, and interface elements do not react when hovering over them

**Comment by PierceNg** [comment]
Can you elaborate what is expected to happen:

- when hovering mouse over (I assume you mean) LCL buttons outside of webview window
- how interface elements (such as?) should react when mouse hovers over them

Let's say I remove the webview activation in ```lclembed```, by making ```TForm1.CreateWebView``` do nothing. The application still runs, just that the main part of the application window occupied by webview is blank. The 'Say Yo to WebView' button doesn't work since there is no webview widget to talk to. The 'Lazarus Say Hello' and 'Exit Program' buttons continue to work. I don't see mouse pointer changes when hovering over these buttons.

If you're referring to within the webview window, that's up to CSS/Javascript of the web page being shown by webview.

**Comment by PierceNg** [comment]
Closing since no further communication. Feel free to re-open or open a new issue with more details.
